<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lev Kolinski">

<title>Exercise_08</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Exercise_08_files/libs/clipboard/clipboard.min.js"></script>
<script src="Exercise_08_files/libs/quarto-html/quarto.js"></script>
<script src="Exercise_08_files/libs/quarto-html/popper.min.js"></script>
<script src="Exercise_08_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Exercise_08_files/libs/quarto-html/anchor.min.js"></script>
<link href="Exercise_08_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Exercise_08_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Exercise_08_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Exercise_08_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Exercise_08_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercise_08</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lev Kolinski </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="getting-started" class="level1">
<h1>Getting Started</h1>
<p><strong>Describing variables (won’t end up using all of them for analyses!):</strong></p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 91%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>wrkslf</code></td>
<td>Whether respondent works for self or not (1=self-employed, 2 = works for someone else)</td>
</tr>
<tr class="even">
<td><code>attend</code></td>
<td>How often respondent attends religious services (range: 0= never, 8 = several times a week)</td>
</tr>
<tr class="odd">
<td><code>polviews</code></td>
<td>How respondent identifies politically (range: 1 = extremely liberal, 7 = extremely conservative)</td>
</tr>
<tr class="even">
<td><code>cappun</code></td>
<td>Does respondent favor or oppose the death penalty for persons convicted of murder (1 = favor, 2 = oppose)</td>
</tr>
<tr class="odd">
<td><code>suicide3</code></td>
<td>Does respondent think that a person has a right to end their own life if they have dishonored his or her family (1 = yes, 2 = no)</td>
</tr>
<tr class="even">
<td><code>xmarsex</code></td>
<td>How respondent feels about extra marital sex (range: 1 = always wrong, 4 = not wrong at all)</td>
</tr>
<tr class="odd">
<td><code>degree</code></td>
<td>Respondent’s education level (range: 0 = less than high school, 4 = graduate degree)</td>
</tr>
<tr class="even">
<td><code>padeg</code></td>
<td>Respondents father’s education level (range: 0 = less than high school, 4 = graduate degree)</td>
</tr>
<tr class="odd">
<td><code>madeg</code></td>
<td>Respondents mother’s education level (range: 0 = less than high school, 4 = graduate degree)</td>
</tr>
<tr class="even">
<td><code>sex</code></td>
<td>Respondent’s sex (1 = male, 2 = female)</td>
</tr>
<tr class="odd">
<td><code>race</code></td>
<td>Respondent’s race (1 = white, 2 = black, 3 = other)</td>
</tr>
<tr class="even">
<td><code>born</code></td>
<td>Was respondent born in the US (1 = yes, 2 = no)</td>
</tr>
<tr class="odd">
<td><code>mcsds6</code></td>
<td>Does respondent like to gossip at times (1 = true, 2 = false)</td>
</tr>
<tr class="even">
<td><code>condom</code></td>
<td>Did respondent use condom last time they had sex (1 = yes, 2 = no)</td>
</tr>
<tr class="odd">
<td><code>marital</code></td>
<td>Respondent’s marital status (1 = married, 2= widowed, 3 = divorced, 4 = separated, 5 = never married)</td>
</tr>
<tr class="even">
<td><code>god</code></td>
<td>Respondent’s confidence in existence of god (range: 1 = don’t believe, 6 = no doubts)</td>
</tr>
</tbody>
</table>
</section>
<section id="contingency-table-1" class="level1">
<h1>Contingency Table 1</h1>
<p>Does weekly (or more frequent) religous service attendance (X) predict whether or not someone is conservative (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># conservative and weekly church attendnace</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> gss18 <span class="sc">|&gt;</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(attend, polviews) <span class="sc">|&gt;</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekly =</span> <span class="fu">if_else</span>(attend <span class="sc">&gt;=</span> <span class="dv">7</span>, 1L, 0L),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">attends =</span> <span class="fu">if_else</span>(weekly <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Weekly"</span>, <span class="st">"Not Weekly"</span>),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">conservative =</span> <span class="fu">if_else</span>(polviews <span class="sc">&gt;=</span> <span class="dv">5</span>, 1L, 0L),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">polview_chr =</span> <span class="fu">if_else</span>(conservative<span class="sc">==</span><span class="dv">1</span>, <span class="st">"Conservative"</span>, <span class="st">"Not Conservative"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(attends,weekly,polview_chr,conservative)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d1, attends, polview_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    attends Conservative Not Conservative
 Not Weekly          495             1243
     Weekly          240              257</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>linear_d1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d1, conservative<span class="sc">~</span>weekly)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = conservative ~ weekly, data = d1)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.4829 -0.2848 -0.2848  0.5171  0.7152 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.28481    0.01110  25.660   &lt;2e-16 ***
weekly       0.19809    0.02354   8.416   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4627 on 2233 degrees of freedom
Multiple R-squared:  0.03074,   Adjusted R-squared:  0.03031 
F-statistic: 70.83 on 1 and 2233 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>logit_d1<span class="ot">&lt;-</span><span class="fu">glm</span>(conservative <span class="sc">~</span> weekly, <span class="at">data =</span> d1, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = conservative ~ weekly, family = "binomial", data = d1)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.1485  -0.8188  -0.8188   1.2066   1.5849  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.92073    0.05315  -17.32  &lt; 2e-16 ***
weekly       0.85229    0.10432    8.17 3.08e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2831.2  on 2234  degrees of freedom
Residual deviance: 2765.1  on 2233  degrees of freedom
AIC: 2769.1

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of 0.1980873 indicates that for respondents who attend religious services at least weekly (X), the probability of being conservative (Y) increase by approximately 0.198 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The positive beta coefficient means that when respondents say they do attend religious services at least weekly, the log-odds of being conservative (Y) increases by approximately 0.8522882.</p>
</section>
<section id="contingency-table-2" class="level1">
<h1><strong>Contingency Table 2</strong></h1>
<p>Does whether or not someone is conservative (X) predict whether or not they agree with capital punishment (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># conservative and capital punishment</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>d2<span class="ot">&lt;-</span>gss18 <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cappun, polviews) <span class="sc">|&gt;</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pro_death_penalty =</span> <span class="fu">if_else</span>(cappun <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">capital_pubisment_chr =</span> <span class="fu">if_else</span>(pro_death_penalty <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Favor"</span>, <span class="st">"Don't Favor"</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">conservative =</span> <span class="fu">if_else</span>(polviews <span class="sc">&gt;=</span> <span class="dv">5</span>, 1L, 0L),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">polview_chr =</span> <span class="fu">if_else</span>(conservative<span class="sc">==</span><span class="dv">1</span>, <span class="st">"Conservative"</span>, <span class="st">"Not Conservative"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(capital_pubisment_chr,pro_death_penalty,polview_chr,conservative)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d2, capital_pubisment_chr, polview_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> capital_pubisment_chr Conservative Not Conservative
           Don't Favor          175              602
                 Favor          523              812</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>linear_d2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d2, pro_death_penalty<span class="sc">~</span>conservative)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pro_death_penalty ~ conservative, data = d2)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.7493 -0.5743  0.2507  0.4257  0.4257 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.57426    0.01264  45.425  &lt; 2e-16 ***
conservative  0.17503    0.02199   7.959  2.8e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4754 on 2110 degrees of freedom
Multiple R-squared:  0.02915,   Adjusted R-squared:  0.02869 
F-statistic: 63.35 on 1 and 2110 DF,  p-value: 2.801e-15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>logit_d2<span class="ot">&lt;-</span><span class="fu">glm</span>(pro_death_penalty <span class="sc">~</span> conservative, <span class="at">data =</span> d2, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = pro_death_penalty ~ conservative, family = "binomial", 
    data = d2)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.6634  -1.3068   0.7598   1.0533   1.0533  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.29924    0.05378   5.564 2.64e-08 ***
conservative  0.79555    0.10256   7.757 8.71e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2778.7  on 2111  degrees of freedom
Residual deviance: 2715.0  on 2110  degrees of freedom
AIC: 2719

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of 0.1750262 indicates that for respondents who are conservative (X), the probability of favoring the death penalty (Y) increase by approximately 0.175 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The positive beta coefficient means that for respondents who are conservative (X), the log-odds of favoring capital punishment (Y) increases by approximately 0.7955526.</p>
</section>
<section id="contingency-table-3" class="level1">
<h1>Contingency Table 3</h1>
<p>Does whether or not someone is an aetheiest (X) predict whether or not someone likes to gossip (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gossip vs believe in god</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>d3<span class="ot">&lt;-</span>gss18 <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mcsds6, god) <span class="sc">|&gt;</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gossip_true =</span> <span class="fu">if_else</span>(mcsds6 <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">like_to_gossip_chr =</span> <span class="fu">if_else</span>(gossip_true <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"True"</span>, <span class="st">"False"</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">atheist =</span> <span class="fu">if_else</span>(god <span class="sc">&lt;</span> <span class="dv">2</span>, 1L, 0L),</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">believe_in_god_chr =</span> <span class="fu">if_else</span>(atheist<span class="sc">==</span><span class="dv">1</span>, <span class="st">"Atheist"</span>, <span class="st">"Not Atheist"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(like_to_gossip_chr,gossip_true,believe_in_god_chr,atheist)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d3, like_to_gossip_chr, believe_in_god_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> like_to_gossip_chr Atheist Not Atheist
              False      32         533
               True      21         549</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>linear_d3<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d3, gossip_true<span class="sc">~</span>atheist)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gossip_true ~ atheist, data = d3)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.5074 -0.5074  0.4926  0.4926  0.6038 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.50739    0.01520  33.388   &lt;2e-16 ***
atheist     -0.11117    0.07033  -1.581    0.114    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4999 on 1133 degrees of freedom
Multiple R-squared:  0.002201,  Adjusted R-squared:  0.00132 
F-statistic: 2.499 on 1 and 1133 DF,  p-value: 0.1142</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>logit_d3<span class="ot">&lt;-</span><span class="fu">glm</span>(gossip_true <span class="sc">~</span> atheist, <span class="at">data =</span> d3, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = gossip_true ~ atheist, family = "binomial", data = d3)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.190  -1.190   1.165   1.165   1.361  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)  0.02958    0.06081   0.486    0.627
atheist     -0.45079    0.28732  -1.569    0.117

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1573.4  on 1134  degrees of freedom
Residual deviance: 1570.9  on 1133  degrees of freedom
AIC: 1574.9

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of -0.11117 indicates that for respondents who are atheist (X), the probability of enjoying gossip at times (Y) decreases by approximately 0.11117 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The negative beta coefficient means that for respondents who are atheist (X), the log-odds of enjoying gossip at times (Y) decreases by approximately 0.45079.</p>
</section>
<section id="contingency-table-4" class="level1">
<h1>Contingency Table 4</h1>
<p>Does whether or not someone is a conservative (X) predict whether or not they used a condom last time they had sex (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># conservative vs condom</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>d4<span class="ot">&lt;-</span>gss18 <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(condom, polviews) <span class="sc">|&gt;</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">yes_condom =</span> <span class="fu">if_else</span>(condom <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">used_condom_chr =</span> <span class="fu">if_else</span>(yes_condom <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No or other"</span>),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">conservative =</span> <span class="fu">if_else</span>(polviews <span class="sc">&gt;=</span> <span class="dv">5</span>, 1L, 0L),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">polview_chr =</span> <span class="fu">if_else</span>(conservative<span class="sc">==</span><span class="dv">1</span>, <span class="st">"Conservative"</span>, <span class="st">"Not Conservative"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(used_condom_chr,yes_condom,polview_chr,conservative)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d4, used_condom_chr, polview_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> used_condom_chr Conservative Not Conservative
     No or other          341              684
             Yes           81              193</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>linear_d4<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d4, yes_condom<span class="sc">~</span>conservative)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yes_condom ~ conservative, data = d4)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.2201 -0.2201 -0.2201 -0.1919  0.8081 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.22007    0.01378  15.971   &lt;2e-16 ***
conservative -0.02813    0.02418  -1.163    0.245    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4081 on 1297 degrees of freedom
Multiple R-squared:  0.001042,  Adjusted R-squared:  0.0002722 
F-statistic: 1.353 on 1 and 1297 DF,  p-value: 0.2449</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>logit_d4<span class="ot">&lt;-</span><span class="fu">glm</span>(yes_condom <span class="sc">~</span> conservative, <span class="at">data =</span> d4, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = yes_condom ~ conservative, family = "binomial", 
    data = d4)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.7050  -0.7050  -0.7050  -0.6529   1.8169  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.26527    0.08151 -15.523   &lt;2e-16 ***
conservative -0.17217    0.14806  -1.163    0.245    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1338.5  on 1298  degrees of freedom
Residual deviance: 1337.1  on 1297  degrees of freedom
AIC: 1341.1

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of -0.02813 indicates that for respondents who are conservative (X), the probability of reporting that they used a condom last time they had sex (Y) decreases by approximately 0.02813 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The negative beta coefficient means that for respondents who are conservative (X), the log-odds of having worn a condom last time they had sex (Y) decreases by approximately 0.17217.</p>
</section>
<section id="contingency-table-5" class="level1">
<h1>Contingency Table 5</h1>
<p>Does whether or not someone thinks suicide is okay if a person has dishonored their family (X) predict whether or not they support capital punishment (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># suicide is okay if dishonored family vs capital punishment</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>d5<span class="ot">&lt;-</span>gss18 <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cappun, suicide3) <span class="sc">|&gt;</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pro_death_penalty =</span> <span class="fu">if_else</span>(cappun <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">capital_punisment_chr =</span> <span class="fu">if_else</span>(pro_death_penalty <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Favor"</span>, <span class="st">"Don't Favor"</span>),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">suicide_okay_if_dishonored_fam =</span> <span class="fu">if_else</span>(suicide3 <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">suicide_if_dishonored_fam_chr =</span> <span class="fu">if_else</span>(suicide_okay_if_dishonored_fam<span class="sc">==</span><span class="dv">1</span>, <span class="st">"suicide okay"</span>, <span class="st">"suicide not okay"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(capital_punisment_chr,pro_death_penalty,suicide_if_dishonored_fam_chr,suicide_okay_if_dishonored_fam)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d5, capital_punisment_chr, suicide_if_dishonored_fam_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> capital_punisment_chr suicide not okay suicide okay
           Don't Favor              444           67
                 Favor              810          118</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>linear_d5<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d5, pro_death_penalty<span class="sc">~</span>suicide_okay_if_dishonored_fam)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pro_death_penalty ~ suicide_okay_if_dishonored_fam, 
    data = d5)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.6459 -0.6459  0.3541  0.3541  0.3622 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     0.645933   0.013523  47.766   &lt;2e-16 ***
suicide_okay_if_dishonored_fam -0.008095   0.037715  -0.215     0.83    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4789 on 1437 degrees of freedom
Multiple R-squared:  3.206e-05, Adjusted R-squared:  -0.0006638 
F-statistic: 0.04607 on 1 and 1437 DF,  p-value: 0.8301</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>logit_d5<span class="ot">&lt;-</span><span class="fu">glm</span>(pro_death_penalty <span class="sc">~</span> suicide_okay_if_dishonored_fam, <span class="at">data =</span> d5, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = pro_death_penalty ~ suicide_okay_if_dishonored_fam, 
    family = "binomial", data = d5)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.4410  -1.4410   0.9349   0.9349   0.9483  

Coefficients:
                               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     0.60121    0.05905  10.181   &lt;2e-16 ***
suicide_okay_if_dishonored_fam -0.03522    0.16397  -0.215     0.83    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1872.3  on 1438  degrees of freedom
Residual deviance: 1872.2  on 1437  degrees of freedom
AIC: 1876.2

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of -0.008095 indicates that for respondents who think suicide is okay if a person has dishonored their family (X), the probability of reporting that they are pro death penalty (Y) decreases by approximately 0.008095 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The negative beta coefficient means that for respondents who think suicide is okay if a person has dishonored their family (X), the log-odds of supporting the death penalty (Y) decreases by approximately 0.03522.</p>
</section>
<section id="contingency-table-6" class="level1">
<h1>Contingency Table 6</h1>
<p>Does whether or not a respondent’s father has more than a high school degree (X) predict whether the respondent has more than a high school degree (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># paternal education vs respondent education</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>d6<span class="ot">&lt;-</span>gss18 <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(degree, padeg) <span class="sc">|&gt;</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">r_greater_than_hs_degree =</span> <span class="fu">if_else</span>(degree <span class="sc">&gt;</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">father_greater_than_hs_degree =</span> <span class="fu">if_else</span>(padeg <span class="sc">&gt;</span><span class="dv">1</span>, 1L, 0L))</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d6, r_greater_than_hs_degree, father_greater_than_hs_degree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> r_greater_than_hs_degree   0   1
                        0 877 136
                        1 454 298</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>linear_d6<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d6, r_greater_than_hs_degree<span class="sc">~</span>father_greater_than_hs_degree)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = r_greater_than_hs_degree ~ father_greater_than_hs_degree, 
    data = d6)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.6866 -0.3411 -0.3411  0.6589  0.6589 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    0.34110    0.01293   26.37   &lt;2e-16 ***
father_greater_than_hs_degree  0.34554    0.02608   13.25   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4719 on 1763 degrees of freedom
Multiple R-squared:  0.09054,   Adjusted R-squared:  0.09002 
F-statistic: 175.5 on 1 and 1763 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>logit_d6<span class="ot">&lt;-</span><span class="fu">glm</span>(r_greater_than_hs_degree <span class="sc">~</span> father_greater_than_hs_degree, <span class="at">data =</span> d6, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = r_greater_than_hs_degree ~ father_greater_than_hs_degree, 
    family = "binomial", data = d6)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.5234  -0.9134  -0.9134   1.4667   1.4667  

Coefficients:
                              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                   -0.65841    0.05782  -11.39   &lt;2e-16 ***
father_greater_than_hs_degree  1.44285    0.11854   12.17   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2408.1  on 1764  degrees of freedom
Residual deviance: 2248.1  on 1763  degrees of freedom
AIC: 2252.1

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of 0.34554 indicates that for respondents whose fathers have greater than a high school degree (X), the probability of themselves having greater than a high school degree (Y) increases by approximately 0.34554 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The positive beta coefficient means that for respondents whose fathers have greater than a high school degree (X), the log-odds of themselves have greater than a high school degree (Y) increases by approximately 1.44285.</p>
</section>
<section id="contingency-table-7" class="level1">
<h1>Contingency Table 7</h1>
<p>Does whether or not a respondent’s mother has more than a high school degree (X) predict whether the respondent has more than a high school degree (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># paternal education vs respondent education</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>d7<span class="ot">&lt;-</span>gss18 <span class="sc">|&gt;</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(degree, madeg) <span class="sc">|&gt;</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">r_greater_than_hs_degree =</span> <span class="fu">if_else</span>(degree <span class="sc">&gt;</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">mother_greater_than_hs_degree =</span> <span class="fu">if_else</span>(madeg <span class="sc">&gt;</span><span class="dv">1</span>, 1L, 0L))</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d7, r_greater_than_hs_degree, mother_greater_than_hs_degree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> r_greater_than_hs_degree    0   1
                        0 1102 192
                        1  535 339</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>linear_d7<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d7, r_greater_than_hs_degree<span class="sc">~</span>mother_greater_than_hs_degree)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = r_greater_than_hs_degree ~ mother_greater_than_hs_degree, 
    data = d7)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.6384 -0.3268 -0.3268  0.3616  0.6732 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    0.32682    0.01167   28.01   &lt;2e-16 ***
mother_greater_than_hs_degree  0.31160    0.02358   13.22   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4721 on 2166 degrees of freedom
Multiple R-squared:  0.07463,   Adjusted R-squared:  0.0742 
F-statistic: 174.7 on 1 and 2166 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>logit_d7<span class="ot">&lt;-</span><span class="fu">glm</span>(r_greater_than_hs_degree <span class="sc">~</span> mother_greater_than_hs_degree, <span class="at">data =</span> d7, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = r_greater_than_hs_degree ~ mother_greater_than_hs_degree, 
    family = "binomial", data = d7)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.4264  -0.8897  -0.8897   0.9474   1.4956  

Coefficients:
                              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                   -0.72262    0.05269  -13.71   &lt;2e-16 ***
mother_greater_than_hs_degree  1.29112    0.10457   12.35   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2923.6  on 2167  degrees of freedom
Residual deviance: 2763.7  on 2166  degrees of freedom
AIC: 2767.7

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of 0.31160 indicates that for respondents whose mothers have greater than a high school degree (X), the probability of themselves having greater than a high school degree (Y) increases by approximately 0.31160 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The positive beta coefficient means that for respondents whose mothers have greater than a high school degree (X), the log-odds of themselves have greater than a high school degree (Y) increases by approximately 1.29112.</p>
</section>
<section id="contingency-table-8" class="level1">
<h1>Contingency Table 8</h1>
<p>Does whether or not a respondent is white (X) predict whether the respondent is self-employed (Y)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># paternal education vs respondent education</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>d8<span class="ot">&lt;-</span>gss18 <span class="sc">|&gt;</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(race, wrkslf) <span class="sc">|&gt;</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  haven<span class="sc">::</span><span class="fu">zap_labels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">r_is_white =</span> <span class="fu">if_else</span>(race <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">r_race_as_chr =</span> <span class="fu">if_else</span>(r_is_white <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"White"</span>, <span class="st">"Not white"</span>),</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">r_is_selfemployed =</span> <span class="fu">if_else</span>(wrkslf<span class="sc">==</span><span class="dv">1</span>, 1L, 0L),</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">r_is_selfemployed_chr =</span> <span class="fu">if_else</span>(r_is_selfemployed<span class="sc">==</span><span class="dv">1</span>, <span class="st">"Self-employed"</span>, <span class="st">"Not self employed"</span>))</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(d8, r_race_as_chr, r_is_selfemployed_chr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> r_race_as_chr Not self employed Self-employed
     Not white               563            49
         White              1466           183</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>linear_d8<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>d8, r_is_selfemployed<span class="sc">~</span>r_is_white)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_d8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = r_is_selfemployed ~ r_is_white, data = d8)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.11098 -0.11098 -0.11098 -0.08007  0.91993 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.08007    0.01226   6.531 8.04e-11 ***
r_is_white   0.03091    0.01435   2.153   0.0314 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3033 on 2259 degrees of freedom
Multiple R-squared:  0.002048,  Adjusted R-squared:  0.001607 
F-statistic: 4.637 on 1 and 2259 DF,  p-value: 0.0314</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic model</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>logit_d8<span class="ot">&lt;-</span><span class="fu">glm</span>(r_is_selfemployed <span class="sc">~</span> r_is_white, <span class="at">data =</span> d8, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_d8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = r_is_selfemployed ~ r_is_white, family = "binomial", 
    data = d8)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.4850  -0.4850  -0.4850  -0.4085   2.2472  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -2.4415     0.1489 -16.392   &lt;2e-16 ***
r_is_white    0.3607     0.1683   2.143   0.0321 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1495.8  on 2260  degrees of freedom
Residual deviance: 1490.9  on 2259  degrees of freedom
AIC: 1494.9

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p><strong>Interpreting linear model</strong>: The beta coefficient of 0.03091 indicates that for respondents who are white (X), the probability of them being self-employed (Y) increases by approximately 0.03091 times, assuming all other factors are held constant.</p>
<p><strong>Interpreting logistic model</strong>: The positive beta coefficient means that for respondents who are white (X), the log-odds of them being self-employed (Y) increases by approximately 0.3607.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>